name: Test and Deploy
on:
  push: 
    branches: [ main ]

jobs:
  test: 
    name: Test
    runs-on: ubuntu-latest
    steps:
   
Edmund, Sheree
2:17 PM (0 minutes ago)
to me

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm test 